max_width = 80
hard_tabs = false
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
wrap_comments = true
comment_width = 80
format_code_in_doc_comments = true
normalize_doc_attributes = true
imports_granularity = "Item" # One import per line — tidy
group_imports = "StdExternalCrate"
blank_lines_upper_bound = 3
enum_discrim_align_threshold = 15
force_multiline_blocks = true
format_generated_files = false
format_strings = true
match_block_trailing_comma = true
struct_field_align_threshold = 5