[package]
name = "demo"
version = "0.1.0"
edition = "2024"

[dependencies]

[profile.dev]
opt-level = 0
debug = true
split-debuginfo = "packed" # optional for Windows, makes smaller .pdb files
debug-assertions = true
overflow-checks = true
incremental = true
